import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/medicine.dart';
import 'package:intl/intl.dart';

class PdfService {
  static Future<void> generateAndPrint(
      List<Medicine> medicines, String userName) async {
    final doc = pw.Document();

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                  level: 0,
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text('Medication Report',
                          style: pw.TextStyle(
                              fontSize: 24, fontWeight: pw.FontWeight.bold)),
                      pw.Text(DateFormat('yyyy-MM-dd').format(DateTime.now())),
                    ],
                  )),
              pw.SizedBox(height: 20),
              pw.Text('Patient Name: $userName',
                  style: const pw.TextStyle(fontSize: 18)),
              pw.SizedBox(height: 10),
              pw.Text('Total Medicines: ${medicines.length}'),
              pw.SizedBox(height: 20),
              pw.Table.fromTextArray(
                context: context,
                border: null,
                headerStyle: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.teal),
                rowDecoration: const pw.BoxDecoration(
                    border: pw.Border(
                        bottom: pw.BorderSide(color: PdfColors.grey300))),
                headers: <String>['Medicine Name', 'Dosage', 'Time', 'Notes'],
                data: medicines.map((med) {
                  return [
                    med.name,
                    med.dosage,
                    DateFormat('hh:mm a').format(med.scheduledTime),
                    '-' // Placeholder for potential notes
                  ];
                }).toList(),
              ),
              pw.SizedBox(height: 40),
              pw.Divider(),
              pw.Text('Generated by Medicine Tracker App',
                  style:
                      const pw.TextStyle(fontSize: 12, color: PdfColors.grey)),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => doc.save(),
    );
  }
}
